### ISSUE TITLE
Any plans to make the remaining 909 drums?

### ISSUE THREAD

**Issue by guytaylor** [tkilla64/eurorack#2]
I am just making your 5 909 drums :)
And was just wondering if you're planning to do any more? e.g. Ride/Crash, toms 
Thanks

**Comment by tkilla64** [comment]
Hello,
Yes, I'm in the making of the Crash/Ride modules right now, so they will be released soon.
I will also do the Tom voices as well at a later point and probably also a summing mixer.

I hope this answers your question :)

**Comment by guytaylor** [comment]
That is great news indeed :)
Is there any chance of CV control over Tune and/or Decay on the toms / ride / crash?

**Comment by tkilla64** [comment]
Sorry, no CV control of the Crash/Ride - the envelopes are fixed.
I haven't started working on the Toms yet, but I will keep that in mind

**Comment by guytaylor** [comment]
Hi there, 
Just thought I check to see if there was any progress on the Toms?
Thanks :)

**Comment by tkilla64** [comment]
I haven't started on that project yet, but it's on my (short-range) radar :) I will do it this year for sure

**Comment by guytaylor** [comment]
That's great news. thanks!
