### ISSUE TITLE
C24 and C25 Undefined in 909 Clap

### ISSUE THREAD

**Issue by CE3-Caspernicus** [tkilla64/eurorack#3]
Hello, I was building the 909 clap module, and I noticed that C24 and C25 are on the board, but not the BOM. What are the values for C24 and C25?

**Comment by tkilla64** [comment]
Hello, I have checked the ibom, schematic diagram and gerber files.

There is no C25 in the design and C24 is defined as a 10nF 0805 capacitor.

Where do you see C25 on the board?

**Comment by tkilla64** [comment]
Btw, maybe you are refering to the 909-rimshot design ?

In that case C24 and C25 are spare pads that you can use if you are having trouble to source 18 nF caps and want to place two capacitors in parallell to get that value.

Hope this answers your question

**Comment by tkilla64** [comment]
Assuming the issue was related to the 909-rimshot module.
Closing issue

**Comment by CE3-Caspernicus** [comment]
Ok, got it. Thank you
